### PR TITLE
Change Tarly to Samwise

### PR DESCRIPTION
**Pull request by vdavez**
I _think_ I have all of the tarly references changed to samwise, and
changed Tarly::Sam to Samwise::Client. That said, the tests are failing.

### CODE REVIEW

**Comment by allalala** [comment]
+1

**Comment by adelevie** [comment]
I want to confirm that this works locally (for someone other than me) before merging.

**Comment by vdavez** [comment]
Just tested locally. It's working.

**Comment by adelevie** [comment]
Ugh to all of this. Ugh!

**Pull request merged**
